### ISSUE TITLE
lirc/lirc_client.h: No such file or directory

### ISSUE THREAD

**Issue by AndreasBackx** [xtruder-archive/pylirc2#1]
When running the installation command after cloning the git in the folder, I get the following output:

<pre><code>running install
running build
running build_ext
building 'pylircmodule' extension
creating build
creating build/temp.linux-armv6l-2.7
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -02 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c pylircmodule.c -o build/temp.linux-armv6l-2.7/pylircmodule.o
pylircmodule.c:38:30: fatal error: lirc/lirc_client.h No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
</code></pre>

Running on latest LIRC version with IRW command working and config done.

**Comment by TheUKDave** [comment]
Did you ever solve this problem? I'm experiencing the same problem

**Comment by ut666** [comment]
Same issue here. Anyone?

**Comment by sagneessens** [comment]
sudo apt-get install liblircclient-dev
This will install the required header file.

**Comment by racegamediy** [comment]
i`m trying to use pylirc2-0.1 with PyPy. but i cannot import it. 

ImportError: No module named pylirc

on python it runs fine. i`ve tried to install it using pypy, easy_install-pypy and pip with no success

also tried to use this but i get another error
import pkg_resources
pkg_resources.require('pylirc')

please help
